/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
}
export interface Donation {
  'id' : string,
  'date' : Time,
  'donorName' : string,
  'amount' : bigint,
  'purpose' : string,
}
export interface Event {
  'id' : string,
  'date' : Time,
  'name' : string,
  'description' : string,
  'location' : string,
  'eventType' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'description' : string,
  'blobId' : [] | [ExternalBlob],
  'itemType' : string,
}
export interface Mantra { 'id' : string, 'title' : string, 'text' : string }
export interface Message { 'id' : string, 'date' : Time, 'text' : string }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'approved' : boolean,
  'passwordHash' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : string,
  'name' : string,
  'availability' : string,
  'mobile' : string,
  'skills' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, string, Time], undefined>,
  'addDonation' : ActorMethod<[string, string, bigint, string], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'addMantra' : ActorMethod<[string, string, string], undefined>,
  'addMessage' : ActorMethod<[string, string], undefined>,
  'approveUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, Time, string, string],
    undefined
  >,
  'deleteAnnouncement' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteMantra' : ActorMethod<[string], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllMantras' : ActorMethod<[], Array<Mantra>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForEvent' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'registerVolunteer' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAnnouncement' : ActorMethod<[string, string, string, Time], undefined>,
  'updateEvent' : ActorMethod<
    [string, string, string, Time, string, string],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [string, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateMantra' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];