/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
});
export const Donation = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'donorName' : IDL.Text,
  'amount' : IDL.Nat,
  'purpose' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'eventType' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'blobId' : IDL.Opt(ExternalBlob),
  'itemType' : IDL.Text,
});
export const Mantra = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'text' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'text' : IDL.Text,
});
export const Volunteer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'availability' : IDL.Text,
  'mobile' : IDL.Text,
  'skills' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'approved' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'addDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addMantra' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteMantra' : IDL.Func([IDL.Text], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForEvent' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'updateEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateMantra' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
  });
  const Donation = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'donorName' : IDL.Text,
    'amount' : IDL.Nat,
    'purpose' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'blobId' : IDL.Opt(ExternalBlob),
    'itemType' : IDL.Text,
  });
  const Mantra = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'text' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'text' : IDL.Text,
  });
  const Volunteer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'availability' : IDL.Text,
    'mobile' : IDL.Text,
    'skills' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'approved' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
    'addDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'addMantra' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteMantra' : IDL.Func([IDL.Text], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForEvent' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateMantra' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };